remote_theme: cotes2020/jekyll-theme-chirpy
markdown: kramdown
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
mathjax:
  source: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js